version: "2"

services:
  postgres:
    image: postgres
    volumes:
      - .private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    logging:
      driver: none
